version: '3.8'
services:
  microservicio1:
    container_name: microservicio1-websocket
    build: ./microservicio-1
    ports:
      - "8080:8080"
    volumes:
      - ./microservicio-1:/app
    command: ["node", "websocket-server.js"]

  microservicio2:
    build: ./microservicio-2
    container_name: microservicio2_web
    ports:
      - "8000:8000"
    volumes:
      - ./microservicio-2:/app
    command: ["python", "manage.py", "runserver", "0:8000"]

  microservicio3:
    build: ./microservicio-3
    container_name: microservicio3_api_historico
    ports:
      - "8001:8001"
    volumes:
      - ./microservicio-3:/app
    command: ["python", "manage.py", "runserver", "0:8001"]

  microservicio4:
    build: ./microservicio-4
    container_name: microservicio4_api_prediccion
    ports:
      - "8002:8002"
    volumes:
      - ./microservicio-4:/app
    command: ["python", "manage.py", "runserver", "0:8002"]
